version: '3'
services:
        nginx:
            image: 'nginx:stable'
            volumes:
                    - '/home/ubuntu/hlot/hlot_fe/dist:/etc/nginx/templates'
                    - '/home/ubuntu/hlot/hlot_fe/nginx.conf:/etc/nginx/nginx.conf'
                    - '/home/ubuntu/hlot/hlot_fe/log:/var/log'
            ports:
                    - "80:80"
            stdin_open: true # 추가
            tty: true        # 추가
            command : bash -c "
                mkdir /var/log/nginx
                chown -R www-data:www-data /var/log/nginx
                nginx -t -c /etc/nginx/nginx.conf
                "
