version: '3.8'
services:
        nginx:
            image: 'nginx:stable-alpine3.17'
            volumes:
                    - '/home/ubuntu/hlot/hlot_fe/dist/:/etc/nginx/templates'
                    - './nginx.conf:/etc/nginx/nginx.conf'   
                    - '/home/ubuntu/hlot/hlot_fe/log:/var/log'
            ports:
                    - "80:80"
            command : sh -c "
                cd /var/log
                mkdir nginx
                chown -R www-data:www-data /var/log/nginx;
                chmod -R 755 /var/log/nginx;
                "        